import type { QuestionTemplate, SkillDefinition } from "./types";

export const QUESTION_TEMPLATES: readonly QuestionTemplate[] = [
  { id: "bond-missing-part", skillId: "number-bond", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 110 },
  { id: "bond-two-parts", skillId: "number-bond", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 80 },
  { id: "addition-sum", skillId: "addition", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 520 },
  { id: "addition-make-ten", skillId: "addition", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 120 },
  { id: "subtraction-difference", skillId: "subtraction", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 430 },
  { id: "subtraction-missing-take", skillId: "subtraction", difficultyBands: ["core", "challenge"], estimatedVariety: 170 },
  { id: "missing-addend-first", skillId: "missing-addend", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 170 },
  { id: "missing-addend-second", skillId: "missing-addend", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 170 },
  { id: "skip-counting-next", skillId: "skip-counting", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 150 },
  { id: "skip-counting-missing", skillId: "skip-counting", difficultyBands: ["core", "challenge"], estimatedVariety: 90 },
  { id: "place-value-value", skillId: "place-value", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 130 },
  { id: "place-value-expanded", skillId: "place-value", difficultyBands: ["core", "challenge"], estimatedVariety: 120 },
  { id: "comparison-symbol", skillId: "number-comparison", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 220 },
  { id: "comparison-greater-less", skillId: "number-comparison", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 160 },
  { id: "money-identify-coin", skillId: "money", difficultyBands: ["review"], estimatedVariety: 24 },
  { id: "money-count-coins", skillId: "money", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 360 },
  { id: "money-compare-amounts", skillId: "money", difficultyBands: ["core", "challenge"], estimatedVariety: 240 },
  { id: "money-shopping-left", skillId: "money", difficultyBands: ["review", "core"], estimatedVariety: 180 },
  { id: "money-simple-change", skillId: "money", difficultyBands: ["core", "challenge"], estimatedVariety: 150 },
  { id: "money-exact-amount", skillId: "money", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 210 },
  { id: "time-analog-read", skillId: "time", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 240 },
  { id: "time-digital-read", skillId: "time", difficultyBands: ["review", "core"], estimatedVariety: 96 },
  { id: "time-match-analog-digital", skillId: "time", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 180 },
  { id: "time-before-after", skillId: "time", difficultyBands: ["core", "challenge"], estimatedVariety: 160 },
  { id: "time-elapsed", skillId: "time", difficultyBands: ["core", "challenge"], estimatedVariety: 120 },
  { id: "fraction-visual-shaded", skillId: "fraction", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 210 },
  { id: "fraction-visual-select", skillId: "fraction", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 180 },
  { id: "measurement-compare-length", skillId: "measurement", difficultyBands: ["review", "core"], estimatedVariety: 110 },
  { id: "measurement-compare-weight", skillId: "measurement", difficultyBands: ["review", "core"], estimatedVariety: 90 },
  { id: "measurement-compare-height", skillId: "measurement", difficultyBands: ["review", "core"], estimatedVariety: 110 },
  { id: "measurement-capacity", skillId: "measurement", difficultyBands: ["core", "challenge"], estimatedVariety: 90 },
  { id: "measurement-ruler", skillId: "measurement", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 180 },
  { id: "graph-most", skillId: "graph", difficultyBands: ["review", "core"], estimatedVariety: 120 },
  { id: "graph-count", skillId: "graph", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 160 },
  { id: "word-addition", skillId: "word-problem", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 190 },
  { id: "word-subtraction", skillId: "word-problem", difficultyBands: ["review", "core", "challenge"], estimatedVariety: 190 },
  { id: "word-missing-addend", skillId: "word-problem", difficultyBands: ["core", "challenge"], estimatedVariety: 100 },
] as const;

export const SKILLS: readonly SkillDefinition[] = [
  { id: "number-bond", title: "Number Bonds", description: "Find parts that make a whole.", prerequisites: [], difficultyBands: ["review", "core", "challenge"], templateIds: ["bond-missing-part", "bond-two-parts"], interactionModes: ["number-entry", "matching"], estimatedVariety: 190 },
  { id: "addition", title: "Addition", description: "Add within 20 and within 100.", prerequisites: [{ skillId: "number-bond", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["addition-sum", "addition-make-ten"], interactionModes: ["number-entry", "multiple-choice", "matching"], estimatedVariety: 640 },
  { id: "subtraction", title: "Subtraction", description: "Take away without negative answers.", prerequisites: [{ skillId: "number-bond", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["subtraction-difference", "subtraction-missing-take"], interactionModes: ["number-entry", "multiple-choice"], estimatedVariety: 600 },
  { id: "missing-addend", title: "Missing Addends", description: "Find the hidden part in an addition equation.", prerequisites: [{ skillId: "number-bond", difficulty: "review" }, { skillId: "addition", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["missing-addend-first", "missing-addend-second"], interactionModes: ["number-entry", "multiple-choice"], estimatedVariety: 340 },
  { id: "skip-counting", title: "Skip Counting", description: "Count by equal steps.", prerequisites: [], difficultyBands: ["review", "core", "challenge"], templateIds: ["skip-counting-next", "skip-counting-missing"], interactionModes: ["sequence-completion", "number-entry"], estimatedVariety: 240 },
  { id: "place-value", title: "Place Value", description: "Read tens and ones.", prerequisites: [{ skillId: "addition", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["place-value-value", "place-value-expanded"], interactionModes: ["visual-selection", "number-entry"], estimatedVariety: 250 },
  { id: "number-comparison", title: "Number Comparison", description: "Compare values using more, less, and equal.", prerequisites: [{ skillId: "place-value", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["comparison-symbol", "comparison-greater-less"], interactionModes: ["multiple-choice"], estimatedVariety: 380 },
  { id: "money", title: "Money", description: "Identify coins, count amounts, compare money, shop, and make exact amounts.", prerequisites: [{ skillId: "skip-counting", difficulty: "review" }, { skillId: "subtraction", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["money-identify-coin", "money-count-coins", "money-compare-amounts", "money-shopping-left", "money-simple-change", "money-exact-amount"], interactionModes: ["number-entry", "multiple-choice", "visual-selection"], estimatedVariety: 1164 },
  { id: "time", title: "Time", description: "Read analog and digital clocks, match times, and solve simple before, after, and elapsed-time questions.", prerequisites: [{ skillId: "skip-counting", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["time-analog-read", "time-digital-read", "time-match-analog-digital", "time-before-after", "time-elapsed"], interactionModes: ["multiple-choice", "matching"], estimatedVariety: 796 },
  { id: "fraction", title: "Basic Fractions", description: "Use pictures for halves, thirds, and quarters.", prerequisites: [{ skillId: "number-bond", difficulty: "core" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["fraction-visual-shaded", "fraction-visual-select"], interactionModes: ["visual-selection", "fraction-coloring", "multiple-choice"], estimatedVariety: 390 },
  { id: "measurement", title: "Measurement", description: "Compare length, weight, height, capacity, and read simple rulers.", prerequisites: [{ skillId: "number-comparison", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["measurement-compare-length", "measurement-compare-weight", "measurement-compare-height", "measurement-capacity", "measurement-ruler"], interactionModes: ["visual-selection", "number-entry", "multiple-choice"], estimatedVariety: 580 },
  { id: "graph", title: "Graphs", description: "Read picture graphs and bar charts.", prerequisites: [{ skillId: "number-comparison", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["graph-most", "graph-count"], interactionModes: ["visual-selection", "number-entry"], estimatedVariety: 280 },
  { id: "word-problem", title: "One-Step Word Problems", description: "Solve short addition, subtraction, and missing-part stories.", prerequisites: [{ skillId: "addition", difficulty: "review" }, { skillId: "subtraction", difficulty: "review" }], difficultyBands: ["review", "core", "challenge"], templateIds: ["word-addition", "word-subtraction", "word-missing-addend"], interactionModes: ["number-entry"], estimatedVariety: 480 },
] as const;

export const skillById = (id: SkillDefinition["id"]): SkillDefinition => SKILLS.find((skill) => skill.id === id)!;
export const templatesForSkill = (id: SkillDefinition["id"]): readonly QuestionTemplate[] => QUESTION_TEMPLATES.filter((template) => template.skillId === id);
