"use client";

import { useEffect, useState } from "react";
import { LESSONS, lessonById } from "../lib/lessons/definitions";
import { commitLessonResult, emptyProgress, lessonIsUnlocked, recommendedLessonId } from "../lib/lessons/progress";
import { generateLessonQuestions, rememberQuestions } from "../lib/lessons/questions";
import { loadProgress, saveProgress } from "../lib/lessons/storage";
import type { CharacterId, LessonId, Question, SavedProgress } from "../lib/lessons/types";

type Screen = "welcome" | "characters" | "map" | "lesson" | "results";
const characters: Record<CharacterId, { name: string; color: string; emoji: string; description: string }> = {
  moss: { name: "Moss", color: "#4f8b48", emoji: "🐿️", description: "a curious forest scout" },
  luna: { name: "Luna", color: "#7865bd", emoji: "🦉", description: "a wise moon owl" },
  ember: { name: "Ember", color: "#d26b42", emoji: "🦊", description: "a bright trail fox" },
};
const Companion = ({ id, small = false }: { id: CharacterId; small?: boolean }) => <span aria-label={characters[id].name} className={`companion ${small ? "small" : ""}`} style={{ "--companion": characters[id].color } as React.CSSProperties}>{characters[id].emoji}</span>;

export default function Home() {
  const [progress, setProgress] = useState<SavedProgress>(emptyProgress);
  const [ready, setReady] = useState(false); const [screen, setScreen] = useState<Screen>("welcome");
  const [lessonId, setLessonId] = useState<LessonId>("number-bonds-1"); const [attempt, setAttempt] = useState(0);
  const [questions, setQuestions] = useState<Question[]>([]); const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [committed, setCommitted] = useState<{ prior: number; stars: number; unlocked?: LessonId } | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => { setProgress(loadProgress()); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  const updateProgress = (next: SavedProgress) => { setProgress(next); saveProgress(next); };
  const startLesson = (id: LessonId) => { const nextAttempt = attempt + 1; setLessonId(id); setAttempt(nextAttempt); setQuestions(generateLessonQuestions(id, `trail-${nextAttempt}`, { history: progress.questionHistory })); setIndex(0); setScore(0); setSelected(null); setCommitted(null); setScreen("lesson"); };
  const answer = (choice: number) => { if (selected !== null) return; setSelected(choice); if (choice === questions[index].correctAnswer) setScore((value) => value + 1); };
  const next = () => { if (index < 7) { setIndex(index + 1); setSelected(null); return; } const finalScore = score + (selected === questions[index].correctAnswer ? 1 : 0); const prior = progress.lessonProgress[lessonId]?.bestScore ?? 0; const beforeRecommendation = recommendedLessonId(progress); const result = commitLessonResult(progress, lessonId, finalScore); const progressWithHistory = { ...result.progress, questionHistory: rememberQuestions(result.progress.questionHistory, questions) }; updateProgress(progressWithHistory); const afterRecommendation = recommendedLessonId(progressWithHistory); setScore(finalScore); setCommitted({ prior, stars: result.starsAdded, unlocked: beforeRecommendation !== afterRecommendation ? afterRecommendation : undefined }); setScreen("results"); };
  const changeCharacter = (id: CharacterId) => { updateProgress({ ...progress, selectedCharacter: id }); setScreen("map"); };
  const current = questions[index]; const recommended = recommendedLessonId(progress);
  if (!ready) return <main className="app-shell loading">Growing Number Forest…</main>;
  return <main className="app-shell">
    {screen === "welcome" && <section className="welcome panel"><div className="forest-orb">✦</div><Companion id={progress.selectedCharacter} /><p className="eyebrow">NUMBER FOREST</p><h1>Ready for a little math adventure?</h1><p>Join {characters[progress.selectedCharacter].name} on a bright forest path.</p><div className="star-total" aria-label={`${progress.totalAdventureStars} adventure stars`}>⭐ {progress.totalAdventureStars} adventure stars</div><button className="primary" onClick={() => setScreen("map")}>Enter Number Forest</button><button className="text-button" onClick={() => setScreen("characters")}>Choose companion</button></section>}
    {screen === "characters" && <section className="panel characters"><button className="back" onClick={() => setScreen("map")}>← Back</button><p className="eyebrow">YOUR ADVENTURE FRIEND</p><h1>Choose a companion</h1><p>Your stars and forest path stay safe.</p><div className="character-grid">{(Object.keys(characters) as CharacterId[]).map((id) => <button key={id} className={`character-card ${id === progress.selectedCharacter ? "chosen" : ""}`} onClick={() => changeCharacter(id)}><Companion id={id} /><strong>{characters[id].name}</strong><span>{characters[id].description}</span><em>{id === progress.selectedCharacter ? "Chosen" : "Choose"}</em></button>)}</div></section>}
    {screen === "map" && <section className="map-screen"><header className="world-header"><div><p className="eyebrow">MAGICAL LEARNING JOURNEY</p><h1>Number Forest</h1><p>Follow the path and light up each lesson.</p></div><div className="header-actions"><div className="star-total">⭐ {progress.totalAdventureStars}</div><button className="icon-button" aria-label="Change companion" onClick={() => setScreen("characters")}><Companion id={progress.selectedCharacter} small /></button></div></header><div className="map" aria-label="Number Forest lesson map"><span className="tree tree-one">🌲</span><span className="tree tree-two">🌳</span><span className="flower">🌼</span><svg className="path" viewBox="0 0 300 900" preserveAspectRatio="none" aria-hidden="true"><path d="M150 850 C55 760 250 685 150 590 S50 425 150 350 S250 190 150 55" fill="none" stroke="#d5a866" strokeWidth="18" strokeLinecap="round"/><path d="M150 850 C55 760 250 685 150 590 S50 425 150 350 S250 190 150 55" fill="none" stroke="#f4d98c" strokeWidth="8" strokeLinecap="round"/></svg><div className="node-list">{LESSONS.map((lesson) => { const completed = progress.lessonProgress[lesson.id]?.completed; const unlocked = lessonIsUnlocked(progress, lesson.id); const currentNode = lesson.id === recommended; const best = progress.lessonProgress[lesson.id]?.bestScore ?? 0; return <article key={lesson.id} className={`lesson-node ${completed ? "completed" : ""} ${currentNode ? "current" : ""} ${!unlocked ? "locked" : ""}`}><button disabled={!unlocked} onClick={() => startLesson(lesson.id)} aria-label={`${lesson.title}: ${!unlocked ? "locked" : completed ? `completed, best ${best} stars` : "unlocked"}`}><span className="node-icon" aria-hidden="true">{!unlocked ? "🔒" : completed ? "⭐" : "✦"}</span><span className="node-copy"><strong>{lesson.order}. {lesson.shortTitle}</strong><small>{!unlocked ? "Locked — finish the lesson before this one" : completed ? `Best: ${best}/8 stars` : currentNode ? "Next adventure!" : "Ready to replay"}</small></span></button>{currentNode && <div className="companion-marker"><Companion id={progress.selectedCharacter} small /><span>Let’s go!</span></div>}</article>; })}</div></div><button className="text-button map-change" onClick={() => setScreen("characters")}>Change companion</button></section>}
    {screen === "lesson" && current && <section className="lesson panel"><header className="lesson-header"><button className="back" onClick={() => setScreen("map")}>← Map</button><div className="progress" aria-label={`Question ${index + 1} of 8`}><span style={{ width: `${((index + 1) / 8) * 100}%` }} /></div><span>{index + 1}/8</span></header><Companion id={progress.selectedCharacter} small /><p className="eyebrow">{lessonById(lessonId).title}</p><h1>{current.prompt}</h1><p className="question-hint">{selected === null ? "Choose your answer." : selected === current.correctAnswer ? "Wonderful thinking!" : `${current.hint} Try another adventure next time!`}</p><div className="choices">{current.choices.map((choice) => <button key={choice} className={`${selected === choice ? (choice === current.correctAnswer ? "correct" : "incorrect") : ""} ${selected !== null && choice === current.correctAnswer ? "reveal" : ""}`} disabled={selected !== null} onClick={() => answer(choice)}>{current.choiceLabels?.[choice] ?? choice}</button>)}</div>{selected !== null && <button className="primary next" onClick={next}>{index === 7 ? "See my results" : "Next question"}</button>}</section>}
    {screen === "results" && committed && <section className="results panel" aria-live="polite"><Companion id={progress.selectedCharacter} /><p className="eyebrow">FOREST ADVENTURE COMPLETE</p><h1>{lessonById(lessonId).title}</h1><div className="score-burst">⭐ {score} / 8</div><p>{committed.stars > 0 ? `You grew your best score by ${committed.stars} star${committed.stars === 1 ? "" : "s"}!` : "You finished every question. Great forest exploring!"}</p><dl><div><dt>Previous best</dt><dd>{committed.prior}/8</dd></div><div><dt>New best</dt><dd>{progress.lessonProgress[lessonId]?.bestScore}/8</dd></div><div><dt>Adventure stars added</dt><dd>+{committed.stars}</dd></div><div><dt>Total adventure stars</dt><dd>⭐ {progress.totalAdventureStars}</dd></div></dl>{committed.unlocked && <p className="unlocked-message">✨ New path unlocked: {lessonById(committed.unlocked).title}!</p>}<button className="primary" onClick={() => setScreen("map")}>Return to Map</button><button className="text-button" onClick={() => startLesson(lessonId)}>Replay lesson</button></section>}
  </main>;
}
